# Generated by Django 2.2.7 on 2019-11-26 21:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('man', django.db.models.manager.Manager()),
            ],
        ),
    ]
